# 4. Java Servlet Container Installation

# 4.1. Java runtime environment: OpenJDK
# Replace with Oracle Java 
- name: Install OpenJDK for 14.04
  apt: name=openjdk-{{ openjdk_version }}-jdk update_cache=yes cache_valid_time=3600
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'

- name: Install OpenJDK for 16.04
  apt: name=default-jdk update_cache=yes cache_valid_time=3600
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial'

- name: Install OpenJDK for 18.04
  apt: name=default-jdk update_cache=yes cache_valid_time=3600
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'bionic'

# 4.2. Servlet container: Apache Tomcat 7
- name: Install Tomcat on Ubuntu
  # package: name="tomcat{{ tomcat.version }}" state=latest
  apt: name=tomcat{{ tomcat.version }} update_cache=yes cache_valid_time=3600
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

## if using tomcat 7, you may uncomment...but not tomcat8
# - name: Copy Tomcat config file
#   copy: > 
#     src=files/tomcat.xml 
#     dest={{ tomcat.path }}/server.xml
#   notify: restart tomcat

- name: Adjust JAVA options
  replace: >
    dest=/etc/default/tomcat{{ tomcat.version }} 
    regexp='JAVA_OPTS="-Djava.awt.headless=true -Xmx128m -XX:\+UseConcMarkSweepGC"' 
    replace='JAVA_OPTS="-server -Xmx1024m -Djava.security.egd=file:/dev/./urandom"'
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
